### ISSUE TITLE
[Heuristique] Ajouter heuristique des captures

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#2]
Pouvoir faire une analyse du goban, possiblement check tous les pions adverses, si on peut identifier une paire avec 2 emplacements vides, rajouter 1 poids heuristique, si on peut identifier une paire adverse avec 1 emplacement pris par un pion allié, 2 poids.

**Comment by abassibe** [comment]
For Discord relink:
Pouvoir faire une analyse du goban, possiblement check tous les pions adverses, si on peut identifier une paire avec 2 emplacements vides, rajouter 1 poids heuristique, si on peut identifier une paire adverse avec 1 emplacement pris par un pion allié, 2 poids.

**Comment by Ragarnoy** [comment]
Les captures ont besoin de l'etat précédent du board pour déterminer si la capture est légale...
