### ISSUE TITLE
[Python] Debug mode

### ISSUE THREAD

**Issue by abassibe** [abassibe/Gomoku#24]
Penser à créer un mode de débug qui permettrais de voir visuellement le parcours de recherche de l'IA.
 - Ajouter une option debug sur l'IHM
 - Ajouter une fonction Rust -> Python avec les données du parcours
 - Créer la fonction d'affichage du debug

**Comment by Ragarnoy** [comment]
Il faudrait que l'affichage debug se fasse dans une nouvelle fenetre (ou un nouveau contexte si on veut), qui nous permet de visualiser l'arbre de possibilités sous forme de graph qui relie les nodes entre eux.
En dessous de ceux-ci (ou en tooltip?) on a leur valeur heuristique, quand on clique sur un node on change de contexte, on ne vois plus que le board du node avec les 2 équipes + le coup joué, et la valeur heuristique du node.
Le clic droit nous permet de "dezoomer" (changement de contexte) et revenir sur la visualisation graph.

Il faudra trouver une manière de gérer proprement le fait qu'on peut avoir plusieurs centaines de milliers de node selon la profondeur....

**Comment by Ragarnoy** [comment]
Bon on remet à plus tard si on a le temps

**Comment by arlaine4** [comment]
This will probably never be done, closing this issue
