### ISSUE TITLE
[Algo] L'IA ne joue pas le coup final et renvoie un node null (none)

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#44]
Dans certains cas, quand l'IA est à un coup de la victoire (ou parfois quand le joueur est a un coup de la victoire) l'IA renvoie un None dans `get_next_move()` à la place de renvoyer un node qui joue le coup final, du coup le programme plante car on ne peut rien faire à part unwrap le `Option<Node>`

**Comment by demonoidv** [comment]
Should be fixed by #49
