### ISSUE TITLE
[Py&Rust] Critères pour coups illégaux (double trois) différents du côté python et du côté Rust

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#45]
Parfois le programme soft lock durant la partie car le côté rust essaie de jouer un coup qui est considéré illégal du côté python.
Fix temporaire : désactiver la règle des double trois côté python.

**Comment by demonoidv** [comment]
![Capture d’écran 2021-03-08 à 18 00 21](https://user-images.githubusercontent.com/20642362/110356916-06c60a80-803b-11eb-9753-748e2bc60645.png)
Here is a picture to put a face on the problem.
In this picture, we can see that it's white turn to move, which is the AI, and the AI already returned a move to play, but it is considered by the graphic part as an illegal move (seems pretty illegal to me too, so I guess the problem must be in the rust part).

What's funny here is that if we hit the hint button then we get the next move the AI wants to play (which is great in this case as it really helps to understand the bug).

**Comment by demonoidv** [comment]
Linked to #37

**Comment by demonoidv** [comment]
I think this one can be closed (fixed by PR #58 and refixed by [this commit](https://github.com/abassibe/Gomoku/commit/88c591ea696f1f4222cd4f592ec3618ac74f2b31))
Nevertheless, the issue #57 is still open and the bug it refers to is still alive.
