### ISSUE TITLE
Bug placement de pion de l'IA après une capture

### ISSUE THREAD

**Issue by arlaine4** [abassibe/Gomoku#46]
Quand le joueur capture un couple de pièce de l'IA, celle ci rejoue son prochain coup toujours au même endroit, a une des deux positions auxquelles se trouvaient ses pièces juste avant d'être capturées. Par contre si elle peut capturer un couple de pièces du joueur, elle préfère parfois faire une capture a son tour (donc après le joueur) plutôt que de jouer son prochain coup a l'endroit ou ses pièces ont été capturés.

**Comment by arlaine4** [comment]
my bad didn't mean to close this issue ^^

**Comment by demonoidv** [comment]
I think this issue can be closed, I don't saw this behavior for quite a long time.
I will push a new version of the algo, after that if someone can confirm that I'm not mistaking it would be really appreciated.
