### ISSUE TITLE
[Algo] Implementation naïve du minimax alphabeta

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#5]
- [x] Objet Node
- [x] Methode de création de node parent/fils
- [x] Node hashing
- [x] Node PartialEq/Eq
- [x] Node PartialOrd/Ord
- [x] Node Debug info/ impl Display (& derive debug)
- [ ] Node Debug info interfacing for python
- [x] Tree system with at least reference to root
- [x] Algorithm with min-maxing

**Comment by abassibe** [comment]
For Discord relink:
Objet Node
Methode de création de node parent/fils
Node hashing
Node PartialEq/Eq
Node PartialOrd/Ord
Node Debug info/ impl Display (& derive debug)
Node Debug info interfacing for python
