### ISSUE TITLE
The AI sometimes just ignores the most interesting move to play

### ISSUE THREAD

**Issue by demonoidv** [abassibe/Gomoku#51]
As you can see in the picture below, sometimes the AI would play a move with really poor value while there is another possible move which actually worth the infinite!

![The said picture](https://user-images.githubusercontent.com/20642362/110358944-30803100-803d-11eb-98f3-4b9e8e0b53a3.png)

In this particular case, it's my turn to play and so we can only see that the hint the AI is giving me is just wrong (doesn't it?). And of course, the AI, when it comes to its turn, didn't play there either (which let me the possibility of playing two half-open four again).

Maybe I'm just a fool and this move is actually forbidden, so it's perfectly normal for the AI not to play this move. But if this is the case, there is an issue in the Python part because it did let me play this specific move.

**Comment by arlaine4** [comment]
No this move shouldn't be forbidden, if you place a stone inside the red circle the two close three and your newly placed stone won't connect, so this shouldn't be a forbidden move
So for me you are right, there is indeed a nice bug

**Comment by demonoidv** [comment]
Fixed by #54
