### ISSUE TITLE
Soft lock AI side - forbidden double three doesn't apply to computer player

### ISSUE THREAD

**Issue by arlaine4** [abassibe/Gomoku#56]
The double three rule isn't applied for the AI wich causes the computer player to softlock
also sometimes, the ai doesn't softlock but just plays a double open three and completly ignores the rule without even doing a softlock

**Comment by demonoidv** [comment]
Your first point is already covered by the already open issue about the same problem.
Your second point is interesting, it could be nice to have that in a comment of #45 instead of creating a dedicated issue
