### ISSUE TITLE
The python part sees illegal move where there is not

### ISSUE THREAD

**Issue by demonoidv** [abassibe/Gomoku#57]
I think the python part does a good job in finding illegal moves, however, I just saw the following:
![Capture d’écran 2021-03-10 à 17 22 53](https://user-images.githubusercontent.com/20642362/110663115-7288ae80-81c6-11eb-94ec-c9dad765cd5d.png)

In this picture, we can see that it's my turn to play and the AI suggests I play where I put a big fat `1` which seems to be a pretty good move to play indeed, but the python part will not let me play it because (I guess) it considers it as an illegal move.

In this particular case, I don't think it's an illegal move because it not really 2 open 3 since there are 2 pieces in common (where a double open three should have only one if I'm not mistaking). Plus, we can see that if I play `1` then the AI is more than likely to play in `2` or `3` (if it plays in `3` then I can play in `2`), and from there we only have a half-open 4 which the AI will probably block at its turn.

I could be wrong but I think there is an issue here.
What do you guys think about it @Ragarnoy @tuturr @abassibe?

**Comment by arlaine4** [comment]
This should be considered as an open split four and not a double open three, It can be defended in positions _**2**_ and _**3**_, so even if Player plays at position _**1**_ it can pretty easily be countered, so this shouldn't be considered as a forbidden move.

**Comment by arlaine4** [comment]
This has been fixed already
