### ISSUE TITLE
[python] Format de chemin de fichier incorrect (textures manquantes etc)

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#6]
Pour pouvoir lancer l'interface il faut changer tous les chemins pour rajouter "../", sinon python ne trouve rien. Il faudrait passer à un format de chemin qui est compatible partout.

**Comment by abassibe** [comment]
C'est bon c'est géré via Pathlib et j'ai ajouté la police de caractère à la DB de Qt au lancement du programme, ce qui évite de devoir l'ajouter à la DB de l'OS.
