### ISSUE TITLE
Fix timer on python interface (Critical)

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#65]
Currently the total timer stops counting whenever the AI is looking for next move.
The expected behavior should be to:

-Stop the player timer (currently the case)
-Start the computer timer (not the case but not even enabled)
-Total timer should continue as if nothing had happened with no latency (not the case)

**Comment by arlaine4** [comment]
Won't be able to do any better (Python side), so Im closing this one this the changes have already been merged to develop.
