### ISSUE TITLE
Python should look for rust_ext in target/release (or target/debug) directory

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#73]
Mostly to save time and because there's no reason to not do it, we should directly look for the necessary python library inside the target folder (and its sub directories), that way we don't have to `mv` everything every time.

**Comment by demonoidv** [comment]
Could be nice to have indeed.
BTW, the script `start_gomoku.sh` now does a pretty good job for you if you don't want to manually move the `.dylib` every time.
