### ISSUE TITLE
Could be nice to have a counter of the turn played

### ISSUE THREAD

**Issue by demonoidv** [abassibe/Gomoku#74]
In order to ease the correction of the project, during which we have to show that our AI is able to beat a human player in a limited amount of turn or at least able to stand up against a human player for a certain amount of turn before losing, I think it could be nice to have a counter for the number of turns that have been played.

I don't know if we want one counter per player or just one global counter, I guess one global counter should enough.

**Comment by arlaine4** [comment]
fixed
