### ISSUE TITLE
Rules that can be turned off/on should have an impact on the rust end or feature should be removed

### ISSUE THREAD

**Issue by Ragarnoy** [abassibe/Gomoku#80]
We either need to disable the option to enable/disable rules or we need to add a static struct or parameters to get_next_move so that the rules on python end and the rust end are the same.

**Comment by Ragarnoy** [comment]
@demonoidv how difficult would it be to disable/enable stuff like captures and illegal moves ?

**Comment by demonoidv** [comment]
> @demonoidv how difficult would it be to disable/enable stuff like captures and illegal moves ?

Should not be too hard to do but it will definitively take time (time we already don't have) I don't think it's a priority since those options should not even be disabled because they are mandatory according to the subject.
